### ISSUE TITLE
DNSSEC server

### ISSUE THREAD

**Issue by jschvartz** [lieser/dkim_verifier#117]
... this is not a new issue, but a request for information.
It seems i have no dnssec available, so the job of controling is not complete.
I am right assuming **my** dns servers (my isp's) must be dnssec compatible ?
If they are not, have you an idea of **public dns servers** that would ?
The addon is currently configured to ignore the fact no dnssec servers are available, and works quite ok (without the small lock in the report ...).

Thanks a lot,
Joel

**Comment by beerisgood** [comment]
for DNSSEC privacy public dns servers:
https://www.kuketz-blog.de/empfehlungsecke/#dns

**Comment by jschvartz** [comment]
Thanks for the documentation.
I tried these DNS, both system wide (win10) or in the options of the addon.
But i still have the same problem, as all my mails says :

    DKCIM Invalid (DKCIM key is not signed by DNSSEC)

(even your mail, received thru github)
I configured the verifier's options (advanced) to say : Treat DKCIM key not secured by DNSSEC as "error"

So maybe the problem is not on my side, but on sender's side (all senders) ?
Or is there something i didn't understand ?

**Comment by jschvartz** [comment]
Certainly for the sender, but not for the receiver, I think ?
The addon is checking directly with sender's email server (or more precisely, with its dns server), as far as i understand.
And if it sends a DKCIM header, both email and dns servers must be correctly configured.
I still think this is a dns issue (my side), but have no clue how to resolve it ...

**Comment by lieser** [comment]
The sending domain must support DNSSEC. Otherwise this feature will not work. Unfortunately the number of domains supporting DNSSEC are very small.
- Github does not support it https://dnssec-debugger.verisignlabs.com/github.com
- PayPal supports it for the [.com](https://dnssec-debugger.verisignlabs.com/paypal.com) domain, but e.g not for the [.de](https://dnssec-debugger.verisignlabs.com/paypal.de) domain
- Amazon also does not support it

Which DNS resolver are you using? The default DNS resolver in the add-on does not support DNSSEC (see also the [FAQ](https://github.com/lieser/dkim_verifier/wiki/FAQ#dnssec-does-not-work) and the [DNS options description](https://github.com/lieser/dkim_verifier/wiki/DNS)).

**Comment by jschvartz** [comment]
Thanks for pointing this out (DNS options description).
I am using javascript dns library !
I will try the libunbound library and let you know.

**Comment by jschvartz** [comment]
Works now fine, sorry i didn't read the doc thoroughly ...
Tested ok with paypal.fr, only one supporting dnssec for me :-(
Many thanks for your time !

**Comment by beerisgood** [comment]
I guess you can close this issue then?
