### ISSUE TITLE
Error connecting to the DNS server on one account but not the other

### ISSUE THREAD

**Issue by n8v8R** [lieser/dkim_verifier#119]
TB 60.0b10 (64-bit) on W10 1709 b16299.579
DV 2.0.0 (`JS DNS library` | checked/enabled `Get DNS from OS`)

---
Sending the same email from the same account to 2 different accounts and both receiving accounts are being accessed via imap in the same TB instance.

For one receiving account (gmail) the verification works with no issue whilst the other one is exhibiting this error

> Error connecting to the DNS server

When accessing the gmail account the error console is exhibiting
 
> DKIM_Verifier.DMARC	ERROR	Ignored error on getting the DMARC policy: DKIM verifier internal error (DKIM_DNSERROR_SERVER_ERROR): rcode: 2 (resource://dkim_verifier/helper.jsm:416:3) JS Stack trace: getDMARCRecord@dkimDMARC.jsm:271:9

Accessing the second receiving account the above shows in the error console too but then _additionally_

> DKIM_Verifier.Verifier	ERROR	DKIM verifier internal error (DKIM_DNSERROR_SERVER_ERROR): rcode: 2 (resource://dkim_verifier/helper.jsm:416:3) JS Stack trace: getKeyFromDNS@dkimKey.jsm:312:9

---

It seems most curious that the second account is introducing the additional error.

Both receiving accounts are on imap port 993 TLS, though perhaps deploying different TLS cipher algorithms. 
On gmail the authentication method is OAuth2 whilst on the other it is Plain text.

TB is behind a nat with a central resolver (unbound) on the network and thus I would expect TB / DV to utilize the same resolver. But perhaps I am wrong there after having discovered 

`extensions.dkim_verifier.dns.nameserver;8.8.8.8`

Having the ip `8.8.8.8` changed to the lan's resolver ip and the DV error for the second account ceased.

I am not really happy that DV is taking the liberty and overriding without my permission the DNS resolver. IMHO the settings of the local machine TB is running on should be honoured.

Changing DNS server string in `extensions.dkim_verifier.dns.nameserver` to `localhost ` or `127.0.0.1` does not work and produces the same error:

> Error connecting to the DNS server

which sort of indicates this being a bug with honouring the local DNS.

---
Curiously even  with an empty DNS server string, e.g. `extensions.dkim_verifier.dns.nameserver` the messages in the receiving Gmail account still getting DKIM verified. Is DV automatically ceeding DNS control to Google with Gmail accounts?

With no DNS server specified DKIM would be expected to fail on any account and it does except for the Gmail account.

---
On top that DKIM verification yields different results on the Gmail account compared to other imap accounts - that is for the same email/dkim header.

Gmail imap account
> Valid (signed by ...) SPF: pass DMARC: pass

Other imap account with 9.9.9.9 as DNS server
> Valid (signed by ...)  `!mark symbol` with overlay `DKIM is not signed by DNSSEC`

Tried alternatively 1.1.1.1 with the same outcome. Both CF (1.1.1.1) and Q9 (9.9.9.9) certainly do proper DNSSEC verification.

What is it with favouring Google DNS and different verfication results?

**Comment by lieser** [comment]
Please enable logging in the advanced options, and provide the output there relevant. This makes it a lot easier to see that is going on.

If you haven't already, please also read the options description at https://github.com/lieser/dkim_verifier/wiki/Options. I get the impression that at least some of you issues are from misunderstanding features.

### For one receiving account (gmail) the verification works with no issue whilst the other one is exhibiting this error
It's because you have enabled ARH reading. The add-on will therefore read the ARH header that google is adding, and dosn't do any DKIM verification at all. The server of your second account properly does not write an ARH header to the e-mail.

From the documentation: https://github.com/lieser/dkim_verifier/wiki/Options#read-authentication-results-header
> If [Read Authentication-Results header is] enabled the add-on first tries to read the DKIM, SPF and DMARC results from the Authentication-Results header instead of verifying the DKIM signature.

---
> Curiously even with an empty DNS server string, e.g. extensions.dkim_verifier.dns.nameserver the messages in the receiving Gmail account still getting DKIM verified. Is DV automatically ceeding DNS control to Google with Gmail accounts?

No, there is no special treatment for Gmail accounts (or any other account). 

Also note that the connection to the server (IMAP/TLS/..) dosn't matter. The add-on is only looking at the raw content of the e-mail, and dos not talk to the server at all.

> With no DNS server specified DKIM would be expected to fail on any account and it does except for the Gmail account.

Not if ARH reading is enabled. Take a look at the log after you enabled debugging to see what is happening.

> On top that DKIM verification yields different results on the Gmail account compared to other imap accounts - that is for the same email/dkim header.

Even if the e-mail does look exactly the same in the normal view, they can be different. Compare the source view of the e-mails to see the differences.

You can also copy the e-mails from one account to another to see that the actual e-mail source is important, not the account in which the e-mail is in (unless you enabled account specif setting of the add-on).

The add-on is not able to do any SPD or DMARC validation locally. That's why this result are only shown if read from an ARH result inside the e-mail.

### DNS problems

> TB is behind a nat with a central resolver (unbound) on the network and thus I would expect TB / DV to utilize the same resolver. But perhaps I am wrong there after having discovered

> I am not really happy that DV is taking the liberty and overriding without my permission the DNS resolver. IMHO the settings of the local machine TB is running on should be honored.

If `Get DNS servers from OS configuration` is enabled, the add-on first trys to read and use the DNS servers configured in the OS. Only if either getting the OS name servers or connecting to them fails are the statically configures used as backup.

Look for a `DKIM_Verifier.JSDNS CONFIG	changed DNS Servers to :` log entry. Is the one from the OS listed here? If not, reading them from the registry fails. You are properly affected by the open issue #116. Please provide more info if you see a different error.

Unfortunately there is no strait forward way to get the OS resolvers from inside the add-on in windows, that I know of. To prevent problems for people that are not that good with PCs, it is therefore in my opinion important to have a reliable backup configured by default.
The usage is also clearly stated in the [Privacy Policy](https://addons.thunderbird.net/en-US/thunderbird/addon/dkim-verifier/privacy/), and can easily be seen (and changed) in the options.

You could try the libunbound resolver. It is using it's own logic for getting the DNS server from the host. Maybe that's working better for you.

> Changing DNS server string in extensions.dkim_verifier.dns.nameserver to localhost or 127.0.0.1 does not work and produces the same error:

`localhost` or `127.0.0.1` means it will try to connect to a DNS server running on your local machine. Unless you are running such a server, this will of course fail.

> What is it with favouring Google DNS and different verfication results?

The only favouring done is that Google DNS was chosen as a default backup. Using a different DNS server should not have any impact on the verification result.

Note that DNSSEC is not working at all with the JS DNS library. See also https://github.com/lieser/dkim_verifier/wiki/FAQ#dnssec-does-not-work

**Comment by n8v8R** [comment]
> It's because you have enabled ARH reading. The server of your second account properly does not write an ARH header to the e-mail.

Correct  about the other server, hence ARH turned off. The results are then the same on both servers.

---

> Note that DNSSEC is not working at all with the JS DNS library.

That one I did not see coming. The option window does not leave much space but I am sure it would be helpful this to be mentioned somehow although conceding that the main purpose of the WE is DKIM/SPF validation and not DNSSEC valdidation.

The DNSSEC Validator add-on has been pulled/removed from TB extensions. It developers are not providing a web extension compatible version. That seems to render any DNSSEC options/integration with DV rather pointless, for W OS that is.

---

> localhost or 127.0.0.1 means it will try to connect to a DNS server running on your local machine. Unless you are running such a server, this will of course fail.

Of course, that was my pea brain not thinking straight. Since the machine a being a DHCP client the DNS upstream ip gets pushed from the DCHP server....

---
That basically sorts this issue and suppose it can be closed thus.

**Comment by lieser** [comment]
> The DNSSEC Validator add-on has been pulled/removed from TB extensions.

You can still download the old *2.1.2.1-signed.1-signed* version from https://addons.mozilla.org/en-US/firefox/addon/dnssec-validator/versions/.

To actually use the dll included in the add-on, you do not need to install it. You can also extract the xpi (it's a normal zip archive) and copy the `plugins/libDNSSECcore-windows-x86.dll` file somewhere. In the DKIM add-ons DNS settings, disable `Path relative to profile directory` and provide the path to the extracted dll.

Note however that almost no site is using DNSSEC.

**Comment by n8v8R** [comment]
Thank you for the hint but since that being a 32-bit DLL and TB being 64-bit that does not seem to work.

And as mentioned in the other thread the 64-bit dll from a later version onger exposes the libunbound function calls.
