### ISSUE TITLE
Icon of senders

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#140]
I see it display an icon near the sender of mails received from LinkedIn.
How to add it also to other mails?

**Comment by lieser** [comment]
Currently this is hard coded into the add-on (mapping: https://github.com/lieser/dkim_verifier/blob/master/data/favicon.json, icons in https://github.com/lieser/dkim_verifier/tree/master/data/favicon). There already exist an issue to change this: #83.

At the moment you can either add them there yourself and create a pull request, or ask me to add sites. Note that E-Mail providers will not be added to the favicon list until #107 is resolved. I also do not add personal sites.

**Comment by ale5000-git** [comment]
I see that some of the sites that I want are already on the list but they still do not display the icon in my e-mails.

Mail of the one present but not working:
noreply@wordpress.org (Wordpress)
bugzilla-daemon@mozilla.org (Bugzilla of Mozilla)


Mail of missing domains:
advertise-noreply@support.facebook.com (Facebook Business)
conferma-spedizione@amazon.it (Amazon Italy)
vistaprint@tm.vistaprint.it (Vistaprint)
noreply@wetransfer.com (WeTransfer)
devnull@yandex-team.ru (Yandex webmaster tools)
service@bingads.com (Bing webmaster tools)

**Comment by lieser** [comment]
Thanks for the list of missing domains. I will add them in the next release.

#### `bugzilla-daemon@mozilla.org`
I have multiple e-mails from Bugzilla, all signed by `mozilla.org`, there the favicon is successfully shown. Please make sure you have the latest 2.0.1 version installed (or `3.0.0pre2` if you are on beta). Previous versions did not yet include the favicon for `mozilla.org`.

If it also does not work with the latest version, make sure DKIM is successfuly validated, and the signing domain shown is `mozilla.org`. If this is the case, please send me an affected e-mail as an .eml file to lieser+dkim@posteo.net, so I can investigate further.

#### `noreply@wordpress.org`
Is this signed by `wordpress.org`? Currently only `wordpress.com` is in the list (added in the latest version).

**Comment by ale5000-git** [comment]
I have version 2.0.1 (since the beta doesn't work with Thunderbird 60.6.1).

bugzilla-daemon@mozilla.org
- Previously it was passing validation, today strangely say that DNS is missing DKIM key, possible caching problem or server problem?
noreply@wordpress.org:
- Signed by wordpress.org

I will send them to you so you can verify.

**Comment by ale5000-git** [comment]
There are also other missing:
web-help@cisco.com (Cisco)
helpdesk_notifications@grandstream.com (Grandstream)
no-reply@youtube.com (YouTube)
notification+zrd61dozzeie@fbworkmail.com (Facebook Workplace)
no-reply@mail.instagram.com (Instagram)
account-security-noreply@accountprotection.microsoft.com (Microsoft team account, I have received it when I have closed an account)
do-not-reply@market.envato.com (Market of WordPress themes)

**Comment by lieser** [comment]
Thanks a gain for the list of missing domains. Will add them too.

`bugzilla-daemon@mozilla.org`:
It seems the DKIM key was deleted from the DNS. This can often happens if a domain is using a new key. As DKIM is intended to be verified by the server shortly after it is received, there normally is not need to keep the old key available for a long time.  
That the add-on is doing (client side verification when the a-mail is viewed) is very unusual for DKIM.

I would recommend enabling the caching of the DKIM keys to avoid this problem. See https://github.com/lieser/dkim_verifier/wiki/Options#caching-of-the-dkim-keys.

I have the key used at that time by mozilla cached locally, and verification and showing of the icon works without problems for the e-mail you send me. I would suggest to postpone further investigation for now, until you have again problems with the icon for an e-mail where verification passes.

**Comment by mortenn** [comment]
Might want to add (email.|)f-secure.com

**Comment by lieser** [comment]
I updated the favicons and default rules. This should also fix #145. Would be nice if you could try it out before I release it.

You can get the pre release from [dkim_verifier-2.0.2pre1.zip](https://github.com/lieser/dkim_verifier/files/3194010/dkim_verifier-2.0.2pre1.zip)

@ale5000-git 
Is `advertise-noreply@support.facebook.com` signed by `support.facebook.com`, or just `facebook.com`? I only added `support.facebook.com` to the favicon list, because to my knowledge facebook users also have a `*@facebook.com` e-mail address. If the e-mail is only signed by `facebook.com`, the favicon will not work.

Also for the default rules, please tell me if the following are not just signed by the top domain, but the complete domain of the e-mail address:
- `vistaprint@tm.vistaprint.it`
- `no-reply@mail.instagram.com`
- `account-security-noreply@accountprotection.microsoft.com`
- `do-not-reply@market.envato.com`

The following there already in the favicon rules, and should have already be showing the favicon:
- `no-reply@youtube.com`
- `account-security-noreply@accountprotection.microsoft.com`

@mortenn 
Please tell me if `email.f-secure.com` is signed only by the top domain, or `email.f-secure.com`

**Comment by ale5000-git** [comment]
@lieser
`no-reply@mail.instagram.com` is signed by `mail.instagram.com`, for the others I can verify them this monday.
I have done some tests and the new pre release seems to work fine.

---------------------------------------------------------
_I have also found other domains to add:_

**Missing sign rule and icon:**
- Sucuri Security <emails@sucuri.net> (signed by hubspotemail.net) => https://sucuri.net/favicon.ico
- Bountysource Alerts <alerts@bountysource.com> (signed by sendgrid.me) => https://bountysource.com/favicon.ico
- <info@consultingroupitaly.com> (signed by aruba.it) => https://www.consultingroupitaly.com/favicon.ico
- <consultingrouphouse@pec.consultingroupitaly.com> (signed by aruba.it) => https://www.consultingroupitaly.com/favicon.ico

**Missing only icon:**
- <postmaster@euroconsumers.onmicrosoft.com> (signed by euroconsumers.onmicrosoft.com)
- Crédit Agricole <noreply@credit-agricole.it> => https://www.credit-agricole.it/favicon.ico
- Cassa dei Risparmi di Forlì e della Romagna <novita@comunicazione.intesasanpaolo.com> (signed by comunicazione.intesasanpaolo.com) => https://www.intesasanpaolo.com/favicon.ico
- <vlc-devel-request@videolan.org> => http://www.videolan.org/favicon.ico
- Twitter <info@twitter.com> => https://twitter.com/favicon.ico
- xda-developers <webmaster@xda-developers.com> => https://forum.xda-cdn.com/images/2015/favicons/favicon.ico
- ricevute di uber <receipts.rimini@uber.com> => https://www.uber.com/favicon.ico
- Blog sul BIM di ACCA <mailing@accasoftware.it> => https://www.acca.it/Portals/0/favicon.ico

**Comment by ale5000-git** [comment]
advertise-noreply@support.facebook.com (signed by support.facebook.com)
vistaprint@tm.vistaprint.it (signed by tm.vistaprint.it)
account-security-noreply@accountprotection.microsoft.com (signed by accountprotection.microsoft.com)
do-not-reply@market.envato.com (signed by market.envato.com)

About it is probably a problem of the fact that emails are old, I will retry if I receive new ones.
About YouTube there is a different problem, it take the space of the icon but it is empty (probably broken icon?)

**Comment by lieser** [comment]
Thanks a lot for the additional domains and information. Will take a lock at it the next days, and add them.

About the problems:
1. `accountprotection.microsoft.com` I looked at it, and to me it looks like the e-mail body got changed, and not a problem with the add-on. The verification also fails with another DKIM verifier.
2. `youtube.com` Could reproduce it. The icon name is misspelled in the domain->icon mapping. Will be fixed in the next version

**Comment by ale5000-git** [comment]
About Microsoft apparently some mail got correct DKIM while some other no, it may be a bug in the mail server.

_I also found some other domains:_

**Missing sign rule and icon:**
WINDAY `<noreply@rewarding.wind.it>` (signed by amazonses.com)

**Missing only icon:**
`<gitlab@mg.gitlab.com>` (signed by mg.gitlab.com)
iliad `<noreply@iliad.it>`
eBay `<ebay@ebay.it>`
Pinterest `<confirm@account.pinterest.com>` (signed by account.pinterest.com)
SGR Servizi `<servizioclienti@sgrservizi.it>`
Travis CI `<success@travis-ci.com>`
Corriere `<re-mailsda@sda.it>`
Staff di Libero `<lo_staff_di_libero@libero.it>`
JUST EAT `<noreplyit@justeat-int.com>`

**Comment by mortenn** [comment]
It is signed by email.f-secure.com
```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=200608; d=email.f-secure.com;
..
From: "F-Secure" <no-reply@email.f-secure.com>
```

**Comment by mortenn** [comment]
But I expect email from @f-secure.com is signed for non-automated email as well.

**Comment by lieser** [comment]
Thank you both for the additional information. Will probably release a new version with this included in the next week. Or you can already try the pre release attached here [dkim_verifier-2.1.0pre1.zip](https://github.com/lieser/dkim_verifier/files/3214302/dkim_verifier-2.1.0pre1.zip) (Note that this version includes #141, so you may see some new warnings).

@ale5000-git 
I did not add the following e-mails, as they seem to be signed by only unrelated domains:
- `emails@sucuri.net`
- `alerts@bountysource.com`
- `info@consultingroupitaly.com`
- `consultingrouphouse@pec.consultingroupitaly.com`
- `noreply@rewarding.wind.it`

For the following I only added the favicon, as I'm unsure if all e-mails from this domains are signed:
- `novita@comunicazione.intesasanpaolo.com`
- `postmaster@euroconsumers.onmicrosoft.com`
- `gitlab@mg.gitlab.com`
- `confirm@account.pinterest.com`

For the others I added both the favicon and a default rule.

**Comment by ale5000-git** [comment]
I have tested all icons in the pre-release and everything is working properly, thanks :)

**Comment by ale5000-git** [comment]
@lieser 
I have found another mail from a bank:
Banca Mediolanum `bmed.news@bancamediolanum.it` => https://www.bancamediolanum.it/favicon.ico
