### ISSUE TITLE
v3.0.1 not working on TB 70.0b2 64-bit

### ISSUE THREAD

**Issue by xsistema** [lieser/dkim_verifier#178]
Just updated to version v3.0.1 on TB 70.0b2 64-bit - and only DKIM title can be seen - message field is empty... Reverify does not help.

**Comment by lieser** [comment]
Just tried it with the 32-bit version of TB 70.0b2, and can not reproduce it.

- Are any errors shown in the error console?
- If no error is shown, please enable debugging, and post the log.
- Please execute `Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULRuntime).invalidateCachesOnRestart();` in the error console of Thunderbird, and restart TB.
- Did you try with all other add-ons disabled?
- What are your display options of the add-on?

**Comment by xsistema** [comment]
After "Reverify DKIM singnature" I'm getting the error message:

```
ypeError: DKIM_Verifier.Display is undefined: 
oncommand chrome://messenger/content/messenger.xul:1
```

**Comment by lieser** [comment]
The error shown for the reverify command is unfortunately not the root cause.

That you get `undefined` for the command I posted is normal.

Please try if with the attached add-on an error is shown: [dkim_verifier@pl-beta.zip](https://github.com/lieser/dkim_verifier/files/3640150/dkim_verifier%40pl-beta.zip)

Besides enabling debugging in the advanced add-on options, also change `extensions.dkim_verifier.logging.console` to `Trace`

**Comment by xsistema** [comment]
Can confirm that dkim_verifier@pl-beta.zip is working.

**Comment by lieser** [comment]
As I didn't fix anything in it (only added logging), my guess is that it was some caching issue. Why the command I gave you didn't help, I don't know.

If my guess is correct, the official release version 3.0.1 should work for you now to.

**Comment by xsistema** [comment]
Yes, installed 3.0.1 again - and it's working..
