### ISSUE TITLE
Dark theme and "From" line

### ISSUE THREAD

**Issue by laaneoks** [lieser/dkim_verifier#181]
Using Thunderbird dark theme.
When e-mail status is "DKIM: No Signature" (holding mouse on the value of "From: ")
Then the value of "From" is not readable
Fix: add background-color as another one have

(
![thunderbird_DKIM_plugin_bug](https://user-images.githubusercontent.com/15246998/67632411-8bcbdc00-f8ab-11e9-952b-d688681e94f0.png)
)

**Comment by lieser** [comment]
This is a problem of the option to highlight the From header. Changing the text color for unsigned e-mail and temporary error to `unset` should solve the problem.

I will change the default in the next release.

**Comment by laaneoks** [comment]
about:config => new values:
extensions.dkim_verifier.color.nosig.background := 'white'
extensions.dkim_verifier.color.tempfail.background := 'white'
Problem solved for me :)

**Comment by lieser** [comment]
Did you also try if setting the text color (`extensions.dkim_verifier.color.nosig.text`) to `unset` instead of changing the background to `white` also works?
Note that this setting is also in the add-ons GUI options under *Display*, so no no need to use `about:config`.

In my test it did work fine, with bot the default and the dark theme. So I plan to make `unset` the new default.

Changing the default background color to `white`  would break it for the default theme.

**Comment by lieser** [comment]
Changed the defaults to `unset`
