### ISSUE TITLE
Probably wrong results?

### ISSUE THREAD

**Issue by joergsteinkamp** [lieser/dkim_verifier#187]
Dear Philippe,

We have a MS-Exchange Server and despite I set "Read Authentications header", the Header DKIM is always wrong. I modified the exact hostname (ironport...) and sender (...@icloud.com). Here are two examples from the same sender:

`Authentication-Results: ironport...; spf=Pass smtp.mailfrom=...@icloud.com; spf=None smtp.helo=postmaster@mr85p00im-zteg06012001.me.com; dkim=hardfail (body hash did not verify [final]) header.i=@icloud.com; dkim=hardfail (body hash did not verify [final]) header.i=@icloud.com; dmarc=pass (p=quarantine dis=none) d=icloud.com`
However, I get "**DKIM Valid (Signed by icloud.com)**"

`Authentication-Results: ironport...; spf=Pass smtp.mailfrom=...@icloud.com; spf=None smtp.helo=postmaster@mr85p00im-hyfv06011401.me.com; dkim=pass (signature verified) header.i=@icloud.com; dmarc=pass (p=quarantine dis=none) d=icloud.com`
And here I get "**DKIM Invalid (E-Mail was modified)**"

Any suggestions, what I might be doing wrong or is the bug on your side? Do you need any additional headers?

Greetings
Jörg

**Comment by lieser** [comment]
I would suggest to enable debugging in the advanced option, and look into the error console to see what is happening. https://github.com/lieser/dkim_verifier/wiki/Debug

What likely happens:
1. Reading of ARH fails because parsing fails (both ARH you posted are invalid, more below)
2. As you did not explicitly disable the add-ons verification, it does it's verification instead (https://github.com/lieser/dkim_verifier/wiki/Options#verify-dkim-signatures)

Problem I noticed with the ARH you posted:
- the first one you posted has `hardfail` as a result for DKIM. But this is not a valid result. See https://tools.ietf.org/html/rfc7001#section-2.6.1 for a list of allowed values
- the `d=icloud.com` at the end for DMARC is not valid syntax. It should probably be `header.d=icloud.com`

**Comment by joergsteinkamp** [comment]
Ok, thanks for your help. I checked sending emails to other servers from various sources and there everything was like expected. So it must be our server introducing those invalid headers.
