### ISSUE TITLE
Key too small issue

### ISSUE THREAD

**Issue by sbsrouteur** [lieser/dkim_verifier#192]
Hello, 

Unless I am missing something, it seems that the sha-1 weak key warning also targets sha-256 keys.

For example email received with following DKIM signature : 
`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=startechweb.onmicrosoft.com; s=selector1-startechweb-onmicrosoft-com;`

is flagged as weak. (most dkim signed message I get, including our own domain show as weak).

is this expected?

**Comment by lieser** [comment]
Are you sure the waring you get is about the hash algorithm (`sha-1`/`sha-256`), and not the RSA key length?

See also #174 and #171. You can get a pre-release with the option for key length exposed (and default changed) from https://github.com/lieser/dkim_verifier/issues/169#issuecomment-570950809

If there is still something unclear, enable debugging in the advanced option https://github.com/lieser/dkim_verifier/wiki/Debug and post the output.

**Comment by sbsrouteur** [comment]
Well the error message says "key too short".
I checked our domain, and our server. I do not get a size option when requesting a new dkim key and the generated key is 1024bits long. Is that not enough?

**Comment by lieser** [comment]
1024bit RSA keys are kind of still Ok (no public knowledge of it yet being broken), but in my opinion defiantly not a good key size. I would recommend to use at least 2048bit (for DKIM keys).

As stated in #171, there is a [proposed standard for DKIM](https://tools.ietf.org/html/rfc8301) that strongly recommends to use at least 2048bit, and forbids keys shorter than 1024bit. That is why the add-on warned since 2.1.0 about keys shorter than 2048bit.
As 1024bit is sadly still more widely used than I thought/hoped, this will change in the upcoming version (#174), and by default no longer warn about 1024bit keys.

**Comment by lieser** [comment]
As you didn't respond yet, I assume your question is answered. If not, feel free to reopen this.

**Comment by sbsrouteur** [comment]
Yes issue is closed. I will wait until the update so that I do not get the warning anymore.
Thankyou

**Comment by lieser** [comment]
Note that https://github.com/lieser/dkim_verifier/issues/169#issuecomment-570950809 contains pre-releases you could already try out. Or you could change `extensions.dkim_verifier.error.algorithm.rsa.weakKeyLength.treatAs` to 2 in TBs settings (the option is already available in the latest release, only not exposed in the GUI)
