### ISSUE TITLE
Syntax error in the DKIM key

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#195]
I have sent you a sample.

**Comment by lieser** [comment]
Seems like a wrong DNS setup. Instead of creating a [CNAME](https://en.wikipedia.org/wiki/CNAME_record), they added the domain it should point to in the TXT record.

Note that according to the Authentication-Results header Google also fails to verify the DKIM signature (with *bad format*).

You could try to report it to the sender. Will close this, as I don't see that there could be done something on the add-ons site.

**Comment by ale5000-git** [comment]
Ok thanks
