### ISSUE TITLE
libunbound / message: "DNS result is bogus"

### ISSUE THREAD

**Issue by Big--Mike** [lieser/dkim_verifier#200]
Hi, 

I have been using DKIM verifier in combination with DNSSEC/TLSA Validator (2.1.2) as libunbound provider for years. 
After updating DKIM verifier to version 2.2.0, I realized, that I get the message "DNS result is bogus" when DKIM verifier tries to verify a signature.
Switching to the JavaScript verifier solves the problem, verification works fine again. 
The JS resolver seems to support DNSSEC (at least if the DNS server does DNSSEC verification), so 
1) are there any disadvantages in case of  switching from libunbound to the JS resolver?
2) is there an updated version of libunbound, which is still working or can you fix the problem on your side?

Kind regards

**Comment by lieser** [comment]
Sorry for the late response.

> I get the message "DNS result is bogus" when DKIM verifier tries to verify a signature.
 
Do you get this on all domains?
If not, it is most likely a miss configuration of the domain. To confirm this you could try out https://dnssec-debugger.verisignlabs.com/.

> The JS resolver seems to support DNSSEC (at least if the DNS server does DNSSEC verification)

The JS resolver **does not** support DNSSEC. If you still see the lock for successful DNSSEC, it is because you enabled the saving of the DKIM keys. If the key was retrieved with libunbound and DNSSEC, it is marked as secure in the database of cached keys.

If the DNS server you use makes it own DNSSEC validation, it probably will not answer queries which fail DNSSEC validation. But you will not see a difference between unsigned domains and domains successfully validated with DNSSEC.

> 1. are there any disadvantages in case of switching from libunbound to the JS resolver?

The main difference is that the JS resolver does not support DNSSEC. libunbound is I think also better at getting the default DNS server from Windows. Otherwise you should not see a big difference.

> 2. is there an updated version of libunbound, which is still working or can you fix the problem on your side?

For me the dll described on https://github.com/lieser/dkim_verifier/wiki/DNS#windows-use-the-libunbound-library-in-the-dnssec-validator still works for TB 32-bit.

Sadly the official unbound site (i.e. https://nlnetlabs.nl/projects/unbound/download/) seems not to contain any dlls exposing libunbound. So besides compiling it yourself, I do not know of a way to get a newer version.

**Comment by Big--Mike** [comment]
Thank you for this great reply. Actually, I try to use DNSSEC, where it is available. So yes, I would get no result instead of a wrong result. (At least I hope so... The test pages indicate it's working...)

First insight: I still clearly need to use libunbound instead of JS resolver (and this was probably the reason I configured it this way, years ago)

I thought, JS resolver was DNSSEC aware (now), since I got the lock, signaling the domain supports DNSSEC.
And I did this only with one domain. I thought the domain was configured probably in DNS as it worked fine with JS resolver (+ lock). 
I completely forgot to think about any caching issues :'(

I switched back to libunbound now and retested the mail. The signature is verified as expected. So it seems, that it was a temporary DNS problem and libunbound is still working fine.

Thanks again, I'm closing the issue now.
