### ISSUE TITLE
Empty tab when add on is enabled

### ISSUE THREAD

**Issue by williwacker** [lieser/dkim_verifier#205]
When double clicking an email the opened tab is empty. Only when I disable this add-on the email gets displayed.

**Comment by lieser** [comment]
Failed to reproduce it just now. Can you please provide the following:
- Add-on version
- Thunderbird version
- Enable debugging in the add-ons advanced options, and post or send me the output of the Error Console (https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages)
- Does this happen with all e-mails?
- Did you try it with all other add-ons besides the DKIM Verifier disabled?

**Comment by williwacker** [comment]
I have now done some analysis and have found that when both Lightning 68.10.0  and DKIM_verifier 3.1.0 are aktive this problem happens. Disabling one of them solves it.
Thunderbird is version 68.10.0
Debugging was just showing some uncaught exceptions with unknown module.
Hope that gives you a hint.
Thanks

**Comment by lieser** [comment]
Unfortunately I still fail to reproduce it. I'm also using TB 68.10.0 and Lightning.

Can you please post the log output, especially the uncaught exception? Please also expand the stack trace, if a small error is shown at the left side of the error message.

**Comment by williwacker** [comment]
This is all I can see in the Error Console.  I don't know how to  get a stack trace.
![grafik](https://user-images.githubusercontent.com/11612373/87678685-86852900-c77b-11ea-9594-a85bba2faaea.png)
Thanks

**Comment by lieser** [comment]
Unfortunately this exception does not have a stack trace or description, no idea how this can happen.
Did you also disable all other add-ons than you took the screenshot? Because the first error seems to come form the conversations add-on.

Besides enabled debugging, please also set `extensions.dkim_verifier.logging.console` to `All` (via Thunderbird's config editor). Then do the following:
1. Disable all add-ons besided DKIM Verifier and Lightning
2. Restart Thunderbird
3. Open the Error console and execute the following two commands:
```js
Services.obs.notifyObservers(null, "startupcache-invalidate");
Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULRuntime).invalidateCachesOnRestart();
```
4. Restart Thunderbird
5. Double click an email to open it in a tab
6. Open the error console and copy the complete output, not just errors

I want to see if any of the add-on code is even called, and if yes how far it's get. For that I need the complete output.

If you do not want to post it here, you can also sent it to me via e-mail to lieser+dkim@posteo.net.

**Comment by williwacker** [comment]
Hi Philippe,
Many thanks for your valuable reply.  Finally it turned out that the Thunderbird Conversations add on was causing this problem. Disabling it made it working.  
Closing this issue.
Thanks
