### ISSUE TITLE
verify don't work for attached/external messages (>=TB 78)

### ISSUE THREAD

**Issue by andreasschulze** [lieser/dkim_verifier#216]
If a user receive a message, it will be verified by the plugin. One can "forward the message as attach" (for example to the same mailbox) In that case the new message has an attach containing the original message. Opened in a new Windows there is also the option "recheck DKIM signature agein" (translated, I see the german version). But this time the Signature is not visable as "green" again.

**Comment by lieser** [comment]
Note that for the current add-on version (3.x), this is a long known bug for IMAP accounts, see #144. As this failed somewhere in the TB code, there unfortunately was never an easy fix.

Unfortunately this will also not work in new add-on (4.x) for TB 78, as the API provided there does not trigger at all, see https://bugzilla.mozilla.org/show_bug.cgi?id=1644038.
Although I will also miss this, especially as it also affects opening of external messages, I don't know yet if I will implement a workaround for this,

I will leave this issue open to keep track about the status for the 4.x version of the add-on.

**Comment by niko-lay** [comment]
Even dkim check not working on .eml load, may be is it possible to enable manual verify via menu? Now all menu items are disabled for such messages.
![image](https://user-images.githubusercontent.com/5228230/164428845-7d2b5b30-1714-4a77-bd8e-27ee5491f798.png)

**Comment by lieser** [comment]
> may be is it possible to enable manual verify via menu?

Unfortunately the problem with external messages is not just that the notification to the addon that a message is viewed does not get triggered.
Manually trying to get the content of the message via the API provided by Thunderbird fails too.
So we unfortunately have to wait until the underlying issue gets fixed in Thunderbird. Or try using experiments as a workaround, but even if I miss this feature myself I don't think it is important enough to use experiments for this.

The not so nice workaround I'm currently using is to copy the message into a local folder in Thunderbird.

**Comment by lieser** [comment]
Will be fixed in the next version. Note that it relies on the fixed bug inside Thunderbird, so only works in 106 or later.
