### ISSUE TITLE
[Request] Clarify DNS requirements in config and/or add support

### ISSUE THREAD

**Issue by mvastola** [lieser/dkim_verifier#231]
Hi,
First off, this extension is awesome, and I thank you. Until recently it had always been rock-solid. Anyway, I just spent a while trying to figure out what was wrong that was causing this addon to tell me there was a problem querying my (`systemd-resolve`) DNS server for domainkey TXT records. 

For whatever reason (I don't know if it was my doing or it was an old Ubuntu default that I kept carrying over), I had `DNSStubListener=udp` in `/etc/systemd/resolve.conf`.

In any case, since `/etc/resolv.conf` defaults to UDP, I had never encountered any issue with the config in the past.

I see the TCP issue was brought up in #42, and I'm guessing this was resolved for the creator of that issue (they never followed up), but I wanted to suggest either making this easier to debug (or, better yet, outright supporting UDP):

There are a bunch of possible solutions that I would leave to your discretion  (any of these would have helped):
-  the ability to explicitly specify UDP, such as by making the accepted server format `[protocol:]host[:port]`
- making dnsjs auto-fallback to UDP if a TCP connection is refused (I'm not sure if the library supports UDP though.)
- Automatically running a test query on the DNS server when exiting the configuration and giving a clear error then.
- Showing a more explicit error message on the DKIM status bar when a query fails. (e.g. something like `Error: Connection to DNS server refused via TCP 127.0.0.53:53`)
- Include a note on the config screen indicating that DNS servers must answer TCP requests (I just chose to get mine from the OS)
- Making one of the two debug/verbose options in preferences enable debugging on the 'experiments' (as it's requisite to use at least one of the two, even if they are experimental).

Also, FWIW, I had a separate issue for `libunbound` that made this even harder to debug. I haven't looked into that issue since I figured out this though.

**Comment by lieser** [comment]
Hi, thanks for the feedback. Out of interest, did you see the info written at https://github.com/lieser/dkim_verifier/wiki/DNS#javascript-dns-library? There the limitation of only supporting TCP is documented.

But I agree, the help available inside the add-on could be better. Especially since I already got the impression that not everyone finds the options description in the wiki.
In the newest version I added a link in the about section of the add-ons option to it, in the hope to improve visibility.

> the ability to explicitly specify UDP
> making dnsjs auto-fallback to UDP if a TCP connection is refused

The way network is done by the JSDNS resolver does not support UDP as far as I know, so at least with the current way unfortunately not really an option.

> Automatically running a test query on the DNS server

This could be an option. Was already thinking that this could be maybe helpful for people who try but fail to use libunbound (because the e.g. no not have the dependency installed).

> Showing a more explicit error message on the DKIM status bar

Will try to find some time to see how this could be improved.

> Include a note on the config screen indicating that DNS servers must answer TCP requests

So far you are only the second person who tried to use a DNS server that only supported UDP. I will consider adding this info in the future. But I think we also have to be careful to confuse people who may not know anything about TCP/UDP, if this is only a rare issue.
If there a more people who hat this problem, please let me know!

> Making one of the two debug/verbose options in preferences enable debugging on the 'experiments'

For libunbound, this should already be the case, for JSDNS it is on my TODO list (currently requires an undocumented setting via `about:config`). But I would have expected errors like a refused connection (because TCP is not supported) to be already logged.
Can you enabled debugging, and show the log what you see?
Or are you aware of a public DNS server that only supports UDP, that I can see for myself?

Note that long term I want to try to use the DNS resolver provided by the OS (#176), in the hope that most DNS issue people currently encounter with the add-on will go away.
But with my current progress, I don't see that coming soon.

**Comment by mvastola** [comment]
> Hi, thanks for the feedback. Out of interest, did you see the info written at https://github.com/lieser/dkim_verifier/wiki/DNS#javascript-dns-library? There the limitation of only supporting TCP is documented.

Sadly, no. I didn't think to check the wiki because (especially since this had been working) it didn't occur to me I had any sort of incorrect configuration.

> Can you enabled debugging, and show the log what you see?

So I'm going to go through everything I did/saw:
a) because I think it's illustrative of some things that could be tweaked
b) as otherwise I'm going to look incredibly stupid later on :stuck_out_tongue: 

The first thing I really did, after a test did and before the error console even -- was check out the settings and try `libunbound`. It seemed the simplest fix. I just tried it again (after turning off experimental debug) and am getting the following sorts of errors:
- `DKIM_Verifier.background	DEBUG	 dns result { data: (1) […], rcode: 0, secure: false, bogus: true }`
- `DKIM_Verifier.Verifier	ERROR	 DKIM_InternalError: DKIM_DNSERROR_DNSSEC_BOGUS`
- `NS_ERROR_NOT_AVAILABLE: `
- `DKIM_Verifier.Verifier	DEBUG	 Exception on DKIM-Signature 1`
- `DKIM_Verifier.SignRules	DEBUG	 shouldBeSigned:  { shouldBeSigned: false, sdid: [], foundRule: false, hideFail: false }`

This made me (understandably, I hope) think my not having DNSSEC on was an issue which made me next go to check this repo for recent changes to DNSJS, and then I read about how this was an alpha release and you were forced to make changes for v84. At that point (seeing no issues for this except an ongoing one for v84) I figured I'd dive in and figure out how DNSJS was broken and submit a PR.  **

Things I am seeing now when using DNSJS:
-  `DKIM_Verifier.JSDNS: Got servers from resolv.conf:  [ { "server": "127.0.0.53", "alive": false } ]`  
   `DKIM_Verifier.JSDNS: no DNS Server alive`
   `DKIM_Verifier.JSDNS: Resolving [selector]._domainkey.[domain]/TXT: DNS server 127.0.0.53 refused a TCP connection.`
  
   Okay, so I'm feeling incredibly dumb now about the last one :flushed: considering my suggestions, but I definitely don't remember seeing it. Looking back, it appears that the 'not alive' status of a server is cached for a bit, and by clicking around my messages for a bit each time before I checked the log again (to make sure I generated new entries), I'm sure I caused myself to miss the retries. 

    In my defense though, there are a few reasons I didn't pay the "not alives" (which I did see) enough attention:
    - I was clearly being oblivious.
    - `libunbound` was literally just able to connect!
    - I was admittedly was chasing the DNSSEC issue so I would have been prone to overlook a message like that.
    - Having debugged enough code, "could not connect" (though not "TCP refused") is a pretty generic error that often means less than it says. I see it used often as a catch-all (i.e. if there's any sort of error with an API, "could not connect" can be the kind of boilerplate message a user gets). Clearly I should have given you more credit, but I thought the other errors I was seeing were the more specific ones I should focus on.

I also got:
- `DKIM_Verifier.background	DEBUG	 dns result { data: null, rcode: 2, secure: false, bogus: false }` 
  `DKIM_Verifier.background	INFO	 DNS query failed with result: { data: null, rcode: 2, secure: false, bogus: false }`
  `DKIM_Verifier.AuthVerifier	DEBUG	 result not saved because DKIM result is a TEMPFAIL`
  
  R[esponse ]code 2, "TEMPFAIL" and "failed with result" made me think there had been a response and that either somehow the authoritative DNS server failed to respond. Or the extension failed to parse the result. 
  Literally the first thing I did was `dig [selector]._domainkey.[domain] @127.0.0.53 TXT`  and saw a reply, so I assumed the problem was "definitely" in the extension, which I later thought I narrowed down to the DNS implementation.

And I got:

- `DKIM_Verifier.Verifier	DEBUG	 Exception on DKIM-Signature 1`
  `DKIM_Verifier.SignRules	DEBUG`	 `shouldBeSigned:  { shouldBeSigned: false, sdid: [], foundRule: false, hideFail: false }`
  `DKIM_Verifier.Verifier	ERROR	 DKIM_InternalError: DKIM_DNSERROR_SERVER_ERROR`
  `DKIM_Verifier.AuthVerifier DEBUG`	 `authResult:`  `{ "version": "2.1", "dkim": [ { "version": "2.0", "result": "TEMPFAIL", [...domain info], "errorType": "DKIM_DNSERROR_SERVER_ERROR", "res_num": 20, "result_str": "Error connecting to the DNS server" } ]  }`

  These reinforced the red herring "DNSSEC" issue I'd been investigating. 

-----------------
** I got deterred on that though because somehow the whole "experiments" folder wasn't showing up in the Thunderbird JS Debugger for me to trace. (I ended up getting it to show up later on fyi -- I think it *might* have been after I added it to `chrome.manifest` but I'm not 100% sure there). But since:
- Thunderbird had been going right past `browser.jsdns.txt(...)` when I hit 'step into'
- it was invoked with `browser.jsdns`
- `browser.jsdns.txt.toString()` returned `[native code]`
... I wasn't entirely sure browser.jsdns wasn't just built into Thunderbird. In the interim I tried to just debug via the error console.

**Comment by lieser** [comment]
Got to see that the log contains the expected `refused a TCP connection` error. But it would probably be good to expose that error in the UI, instead of just showing an general DNS error message.

> This made me (understandably, I hope) think my not having DNSSEC on was an issue

Normally, using a DNS server that does not support DNSSEC, should not result in a bogus DNS result. If there is no DNSSEC available at all, the result should be `secure: false, bogus: false`.

To see if the domain itself has a setup problem with DNSSEC, using https://dnssec-analyzer.verisignlabs.com worked good for me in the past.
To see if there is a problem with your DNS server, using dig is probably the best way.

> Looking back, it appears that the 'not alive' status of a server is cached for a bit

Yes, this is cached until the DNS settings change (or TB restarted).
The intend is that if one is offline, or the user added only non working DNS servers, the add-on doesn't try to do non working network requests all the time. And show in the header always the `Validating...` for several seconds.
But this sometimes cause confusion/problems. Improving it is on my (to long) todo list.

> R[esponse ]code 2, "TEMPFAIL" and "failed with result" made me think there had been a response and that either somehow the authoritative DNS server failed to respond.

yeah that part is probably confusing for someone who knows DNS, but not the add-on code. The current implementation (for both resolvers) for error handling just sets the rcode to `ServFail` if there is an error thrown by the implementation itself: 
https://github.com/lieser/dkim_verifier/blob/6bc18bd1d93f66100691aebf970edcc4a2430004/experiments/jsdns.js#L87

This is something that should probably be reconsidered.

> I got deterred on that though because somehow the whole "experiments" folder wasn't showing up in the Thunderbird JS Debugger for me to trace.

Where you using `Debug add-on` > `Inspect`? That does not work for experiments, as they do not run in the context of the add-on.
You have to instead use the debugger for Thunderbird itself, available under `Tools` > `Developer Tools` > `Developer Toolbox`. If the add-on is installed the normal way, if will show up under `jar://<path to TB profile>/extensions/dkim_verifier@pl.xpi!/experiments`. If you are using load temporary add-on, it will shows up somewhere else in that tree.

**Comment by Tazmaniac** [comment]
TCP is mandatory for "on the wire" DNS protocol since decades. An IP listening resolver must use/listen on  UDP **AND** TCP.
If your (stub-)resolver is non compliant/does not support TCP use another one.
Don't lost your time on this, just add a warning on the config page.

Hint: for systemd don't use convoluted configuration, use default "DNSStubListener=yes" to listen on UDP and TCP. These "upd" and "tcp" config values are non sense and should never have been exposed for general use.

**Comment by tadpole2077** [comment]
Tazmaniac is correct on fallback flow UDP > TCP.   
Optimally for DKIM, using UDP (port 53) as primary protocol for DNS queries will result in much faster responses from DNS servers - likely reducing instances of DNS query timeouts(from current primary use of TCP).  TCP calls are quite heavy due to 3 way handshakes but reliable.  UDP calls are not reliable so need TCP as fallback. 

In practical terms, when i'm scrolling though email (and a lot of junk), there can be a 1 to 3 second(or more) delay on signature validation with new DNS queries - not in the cache,  if DKIM could use UDP that would i believe result in much faster responses, improved user experience and less processing load per mail signature check.

**Comment by Tazmaniac** [comment]
It is a little more complicated than that.
The TCP fallback/mode is here not for reliability purpose, but for UDP fragmentation avoidance. UDP fragmentation is needed over a certain response parket size. But UPD fragmentation it impractical because of technical problems in real life and because of security problems. So we switch to TCP.

The TCP latency is presently not a real problem. libunbound use persistent TCP connections, and jsdns too i think.
The problem is that we actually do not cache the result. Neither the DNS result nor the dkim validation result. If you use libunbound (for DNSSEC), you will do a complete end to end DNSSEC validation. It is expensive. Recomputing the complete DKIM validation is expensive too.
So when the caching of the key will be re-implemented, things/latency will be better (landed in git).
As I am on 86.0b3, i need to wait to be able to test anything. Too much legacy support is removed in 86.0 to get  4.0.0pre4 in a working state.

**Comment by lieser** [comment]
@Tazmaniac Note that the master branch of the add-on should now work again with the latest daily version of TB (https://github.com/lieser/dkim_verifier/commit/74c0af2d69c2fd7b9a4a1d8dc8a8bb9ba025930a). Let me know if I should create a packed version of the add-on for you.

**Comment by Tazmaniac** [comment]
It would be great, thank you, but I could wait the next pre-release.

**Comment by lieser** [comment]
Connection issues are for the JSDNS resolver not longer internally treated as an rcode `ServFail` being returned. And will therefore not longer show up in the log as if we got some failure result form the DNS server. Hopefully this avoids some confusion for people who look at the log but are not familiar with the internals.

Note that the same is not true for the libunbound resolver. The library seems to use the rcode `ServFail` to indicate also connection failures. So no easy way to differentiate between a connection issue and a server responding with rcode `ServFail`. This will be a limitation we will just have to live with.

I will consider this closed for now. If there is still something I missed please create a new issue.
