### ISSUE TITLE
Auth-Res only, DKIM failures cause "Internal Failure"

### ISSUE THREAD

**Issue by shirikodama** [lieser/dkim_verifier#232]
Hi, 

I turned the active DKIM verifier off and instead just relied on the upstream Auth-Res. When a DKIM signature failure is detected in the auth-res, it is  displaying "Internal Error" rather than something more helpful. I tracked this to arhDKIM_to_dkimSigResultV2 () causing the translatable error message to not be found which causes the caller to throw an error. 

at line 436, it seems like it should be something like this instead:

//dkimSigResult.errorType = "";                                                                            
dkimSigResult.errorType = "DKIM_SIGERROR_BADSIG";

either that or figuring out why the arhDKIM.reason is empty might be even better. I can supply the offending email if needed. also, I just downloaded the extension today, so it should be fresh.

Michael Thomas, one of the authors of rfc 4871 and implementor of the first DKIM code (Murray was about a day later)

**Comment by lieser** [comment]
Thanks a lot for reporting. I can reproduce this if ARH has the `fail` result, but does not contain a `reason=`.

I have not yet decided how I will handle this case. Currently tending to just show `Invalid` as the result, instead of `Invalid (Signature is wrong)` (how it would show with your suggestion), or something like `Invalid (unknown)`

**Comment by lieser** [comment]
This should be fixed now, you can get a test version at https://github.com/lieser/dkim_verifier/issues/199#issuecomment-774676192.

Please reopen the issue if it is still not working for you.
