### ISSUE TITLE
Localization - Support for Spanish Localization

### ISSUE THREAD

**Issue by tadpole2077** [lieser/dkim_verifier#239]
Add support for Spanish Localization, and subfolder for ES-es under _locales.  
Using European Castilian Spanish

**Comment by tadpole2077** [comment]
I'm working on this now, should be done within the next week.

**Comment by lieser** [comment]
Thanks for letting me know, and nice to see that the add-on will get another translation. If there is something unclear with the strings, don't hesitate to ask.

Note that on https://www.babelzilla.org someone named *strel* started a Spanish translation a while back, but never finished it.

Attached is what he translated. Note that it is still in the old format
[dkim.properties.txt](https://github.com/lieser/dkim_verifier/files/5974281/dkim.properties.txt).

Please let me know if you integrate his work instead of just starting from scratch, so that he will get attributed in that case.

**Comment by tadpole2077** [comment]
Ok thanks for the additional legacy work file reference, i'll cross-reference/review it when defining the new ES translations. but likely will not use it directly (of course some strings will be identical).  looks like Strel got about 40% though the message list.

**Comment by tadpole2077** [comment]
2021_02_19 50% complete..  ETA 1 week more

**Comment by tadpole2077** [comment]
Task completed, ready to commit to master.  Tested on local env - all good.
o	./_locales/es_ES/*  {4 files}
o	./chrome.manifest
o	./install.rdf
o	./content/options.html

How should I do the commit as commit access permission is locked?

**Comment by lieser** [comment]
Nice to hear you are finished, and sorry for the late reply.

GitHub works mainly with pull request for collaboration.

You need to:
1. create a fork https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
    - see also https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks
2. push your changes to your fork
3. create a pull request https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Note that `./chrome.manifest` and `./install.rdf` are outdated files that you didn't have to change (`./install.rdf` has already ben deleted). As you seem to be new to git/GitHub, don't worry about cleaning that up.
If you keep the `Allow edits from maintainers` checkbox enabled then you create the pull request, I should be able to do that myself.

**Comment by tadpole2077** [comment]
Grand, i had already forked the project last year, and was working off of that. I just committed and added a pull request above.  

Actually had to revert out all unrelated stuff that i'm playing with regarding load testing of DNSServer queries and intermittent timeouts to narrow the pull to related files for ES localization.  

What's next on the development pipeline, happy to help out, just id issues that need review.

**Comment by lieser** [comment]
Will leave this open as a reminder to upload the Spanish descriptions to ATN.

> What's next on the development pipeline

I'm in the process of moving the last missing pieces from the 3.x Version to the 4.x Version. Afterwards the short term plan is in https://github.com/lieser/dkim_verifier/milestone/16.
I currently don't have a clear long term plan.

> happy to help out, just id issues that need review.

It is a little unclear to me, are you offering to review changes I do, or are you interested in doing some development work yourself?
If it is doing development yourself, you could do any of the open feature request that interests you. I could also look over them and try if I see an easy starting issue.

If more people start to contribute, I also think this repo should get some CI, instead of me running the tools (unit tests, eslint, type checking) just locally.
This could also be something you could look into.

**Comment by lieser** [comment]
Translation is added to ATN: https://addons.thunderbird.net/es/thunderbird/addon/dkim-verifier/
