### ISSUE TITLE
TB115: Message header display is blocked while DKIM verifier is working

### ISSUE THREAD

**Issue by jikamens** [lieser/dkim_verifier#386]
I received several messages recently which DKIM Verifier took a long time to validate, presumably because of some sort of DNS delay but who knows. When I clicked on either of these messages in my inbox, the header display (From, To, Subject, etc.) remained set to the values for the _previous_ message I was viewing, until DKIM Verifier finished.

DKIM Verifier should be working asynchronously. It shouldn't block proper display of the other header fields while it's working.

**Comment by jikamens** [comment]
Hmm, I'm not actually sure this is a DKIM verifier issue. I've got DKIM Verifier disabled and I'm still seeing delays displaying message headers. Need to investigate further.

**Comment by lieser** [comment]
Thanks for the update. All the code in the add-on that could potentially take some time should already be async. Including the one for getting the DNS result.

From you description it sounds a little like maybe something is blocking in Thunderbird's `gMessageListeners`.
But what this add-on does there should be nothing that that takes long (https://github.com/lieser/dkim_verifier/blob/v5.3.1/experiments/dkimHeader.js#L1072-L1158).

Maybe it is something else, that also prevents `browser.messageDisplay.onMessageDisplayed` from being triggered? That would explain why the DKIM result is only shown after then the rest is unblocked, because the verification only start after the unblock.

If you think it could still be related to the DKIM Verifier, please enable the logging in the advanced option. The time stamps of the log messages could maybe give a hint.

**Comment by jikamens** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1851871

**Comment by lieser** [comment]
Nice that you found the problem, and thanks for the link to the upstream bug. So looks like it is a problem in Thunderbird that is unrelated to this add-on.

I will close this issue. If you still think there is something that should be changed in the add-on feel free to reopen it.
