### ISSUE TITLE
Conversations addon's pill for DKIM verfier is missing

### ISSUE THREAD

**Issue by sha-265** [lieser/dkim_verifier#395]
If I'm not a complete dumbass who unable to find this "pill", there is a bug on TB (115.3.1) with Conversion addon (v5.3.1) and DKIM verifier (v4.1.3), that cause this pill to disappear.

Help me find this pill (if it exists):
![image](https://github.com/lieser/dkim_verifier/assets/4103710/16d207c1-ae1b-47d9-b8cb-09a0b6b5182e)

And here is the same email opened in the default viewer:
![image](https://github.com/lieser/dkim_verifier/assets/4103710/31a62229-68f8-4b3c-b6bd-aea3ef15d137)

The only thing that could be relevant that I found in TB's error log:
```
Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
    <anonymous> chrome://conversations/content/stubWrapper.js:21
6 stubWrapper.js:21:13
    <anonymous> chrome://conversations/content/stubWrapper.js:21
```

Thanks.

**Comment by Standard8** [comment]
The problem appears to be this bit of the code: https://github.com/search?q=repo%3Alieser%2Fdkim_verifier+tab.url%3F.startsWith%28%22chrome%3A%2F%2Fconversations%2F%22%29&type=code

I suspect this due to how the Thunderbird rework has changed all the tab processing - the tab no longer has a url field option, and so `chrome://conversations` can't be matched.

I'm not sure of an easy option of what to do there, except for maybe detecting if Conversations is installed/active and running it regardless.

**Comment by lieser** [comment]
Thanks for reporting the issue, this should be fixed now. If you want to try it out already you can use the following version:
[dkim_verifier@pl-2023-10-22-8ce2309.zip](https://github.com/lieser/dkim_verifier/files/13063906/dkim_verifier%40pl-2023-10-22-8ce2309.zip)

@Standard8 You there correct about the problematic code.
I extended your proposed check a little to work with the case that a message is viewed in a tab or windows (in the classic view).

I noticed that if Conversations is installed `browser.messageDisplay.onMessageDisplayed` is not triggered even then viewing single messages in Thunderbird's 3pane tab. I guess this is something Conversations prevents?
This is nothing that interferes with my add-on, it actually means the check I do fo conversation there is not needed currently. I still decided to leave it in in case it changes in the future.
