### ISSUE TITLE
works on OSX

### ISSUE THREAD

**Issue by hdatma** [lieser/dkim_verifier#46]
Please append to https://github.com/lieser/dkim_verifier/wiki/DNS

libunbound library under OSX

1. Install libunbound2
2. select the DKIM_Verifier's Preferences > General > DNS
3. select Resolver "libunbound"
4. Disable "Get DNS server from OS configuration"
5. Set DNS server to 127.0.0.1:53
6. Disable Path relative to profile directory
7. Set path to [your-prefix-here]/lib/libunbound.2.dylib
8. Restart Thunderbird.

Tested under OSX 10.10.4 with libunbound 1.5.4, Thunderbird 38.1.0, and DKIM verifier 1.3.5.

**Comment by lieser** [comment]
Thanks for the install instructions. I have a few questions I hope you could answer before I put it in the wiki.

>1. Install libunbound2
From where? Maybe it's because I'm not an OSX user, but I wouldn't know this, and also didn't find anything with a quick google search.

>4. Disable "Get DNS server from OS configuration"
>5. Set DNS server to 127.0.0.1:53
Are you sure this is needed, and not something special for you configuration? Because the libunbound resolver should work with any DNS server.

**Comment by hdatma** [comment]
unbound is a caching DNSSEC resolver, to be installed in the client machine (hence the IP address 127.0.0.1 on port 53). The official packages are available from the developers page: 

https://www.unbound.net/downloads/

**Comment by lieser** [comment]
Have added it (https://github.com/lieser/dkim_verifier/wiki/DNS#osx-install-from-source)
