### ISSUE TITLE
Verifies only first of multiple DKIM signature headers

### ISSUE THREAD

**Issue by scoolen** [lieser/dkim_verifier#48]
I've tested the Add-On (1.3.6) in Thunderbird (38.2.0) with an email with multiple signatures.

From the RFC:
> A message can contain multiple signatures from the same or different organizations involved with the message.

The first signature gets correctly verified, but reports a warning (_"From is not in Signing Domain"_). The second one (below it) gets ignored, which is the one that _does_ actually match the From domain.

**Comment by scoolen** [comment]
To amend to that. I checked a similar email (from the same sender and with the DKIM headers in the same order) and in that second email it verifies the _other_ signature.

**Comment by scoolen** [comment]
Never mind. I've looked at the console debug messages and it clearly says:
> DKIM_Verifier.Verifier	DEBUG	2 DKIM-Signatures found.

I think I expected the UI to show feedback for multiple signatures.

**Comment by lieser** [comment]
The reason the UI does not show multiple signatures is that at least I am in most cases only interested in one signature, the one that verifies without issues.
And because I found no good way to display additional signatures without needing more space in the header, I decided against showing multiple signatures in the header.
In case you need the showing of multiple signatures in the UI, it could be added as an optional feature.

That the add-on is doing in case of muttiple signatures is sorting them with the following criteria:
1. SUCCESS / TEMPFAIL / PERMFAIL
2. has warnings
3. From is in SDID / List-ID is in SDID

So in your case the signature that matches the SDID should be the on shown if it is valid, and not the one that doesn't.

**Comment by scoolen** [comment]
That's exactly what happens. Great add-on btw!

**Comment by counterpoint** [comment]
Thanks for the comment on #124. Unfortunately, I cannot see how it deals with the problem. Both DKIM signatures are entirely valid according to both check-auth@verifier.port25.com and autorespond+dkim@dk.elandsys.com. The diagnosis from port25 includes:
In respect of the mail relay domain DKIM record "Result: pass (signature verifies; identity doesn't match any headers)"
And in respect of the sending domain DKIM record "Result: pass (matches From: martin@example.com)" [domain changed]
Yet the add-on refers only to the mail relay DKIM record and warns that it is not the sending domain. The error console doesn't tell me anything additional.
