### ISSUE TITLE
yahoo.de in standard rules

### ISSUE THREAD

**Issue by bege10** [lieser/dkim_verifier#63]
All messages I receive from @yahoo.de accounts are not signed. Remove from standard rules?

**Comment by lieser** [comment]
Does this only only apply to recent e-mail, or also old ones? Do you yourself have a yahoo.de account?
I'm asking because the last e-mail I received from yahoo.de (23.08.2015) was signed. I find it a little hard to believe they stopped doing so (DKIM key is still available and they are using DMARC).

**Comment by bege10** [comment]
Hi,
sorry for my late response, I was out of town.

The problem turned out to occur only with one yahoo.de account I 
received frequent messages from. I couldn't find out why these messages 
where not signed by yahoo.de.
Sorry for having bothered you.
Regards
bege

**Comment by lieser** [comment]
Thanks for the clarification.

The person is probably not using his yahoo.de account to send the e-mails, but a different server. Many e-mails server allow sending e-mails with arbitrary from addresses (especially if you can prove ownership of the address).
If you haven't, I would suggest to make an exception for this yahoo.de address. For example by clicking the "Other actions" button in the e-mail header, and selecting "Add must be signed exception".
