### ISSUE TITLE
Gmail 'All Mail' breaks verification

### ISSUE THREAD

**Issue by dominicraf** [lieser/dkim_verifier#86]
I notice that Gmail 'Sent Items' does not break verification so I guess you have some code that knows emails in here are never signed; however Gmail 'All Mail' does break it for emails sent by self which show in 'red'. Would be neat if this could be fixed.

Thanks for this great add-on - terrific work!

**Comment by lieser** [comment]
What is the exact error you are getting: that the message should be signed, or that the signature is invalid?

If the error is "should be signed":  
Outgoing messages should not only be detected if they are in the send folder. They are also detected as outgoing if the address in the From header is included in one of the identities configured in Thunderbird for the account.  
Can you please check if this is the case?

If the error is "signature is invalid":  
This error is not hidden for outgoing messages, so it is expected behavior.


Note that you can ignore both the above errors for specific From addresses with a custom [sign rule](https://github.com/lieser/dkim_verifier/wiki/Sign-rules) of [type 2/3](https://github.com/lieser/dkim_verifier/wiki/Sign-rules#rule-type)

**Comment by dominicraf** [comment]
Thanks Philippe you are right, the problem was that on this account I did not have an identity configured to match the sent address (it is just for monitoring emails sent,not for sending). I fixed this, still all the existing emails show wrong but I presume that new emails will show correct (green). Thanks for your help.

**Comment by lieser** [comment]
As long as you have disabled the saving of the result, this should also affect old messages.

What Version of Thunderbird and the add-on are you using?
Would you be willing to install a custom version with more debugging messages included?

**Comment by dominicraf** [comment]
T'brid 45.8, now upgraded now to 52, DKIM Verifier 1.6.5. Sent messages (in whatever folder) now show as 'No Signature' which is correct. I'm happy to install a custom version it if can help you.

**Comment by lieser** [comment]
If I understand you correctly, this is now fixed for you, isn't it? Then there is now need.

**Comment by dominicraf** [comment]
yes it's all working thank you.
