### ISSUE TITLE
Valid sig for Sender:, invalid sig for From:

### ISSUE THREAD

**Issue by gene-hightower** [lieser/dkim_verifier#88]
I get mail from a list that sets the Sender: header to the list owner and attaches a valid DKIM sig.  The original sig now fails as the list re-writes a bunch of stuff so the sig that goes with the original From: domain is no longer valid.

Sure would be nice to see that the sender dig is good and matches the Sender: header.

BTW: no ARC chain for this list.

Great plugin thanks!

**Comment by lieser** [comment]
What do you want to achieve with this? That the DKIM signatures by the list (which should already be the one shown to you in the header) does not generate the "From is not in the signing domain" warning?

If yes, then as long as the mailing list is also setting the `List-ID` header, you should already be able to achieve this with a [sign rule](https://github.com/lieser/dkim_verifier/wiki/Sign-rules) of type 1 or 2, matching to the specific List-Id (leave domain empty, and set From to `*`)

**Comment by gene-hightower** [comment]
On 2017-06-04 07:03, Philippe Lieser wrote:

> What do you want to achieve with this? That the DKIM signatures by the
> list (which should already be the one shown to you in the header) does
> not generate the "From is not in the signing domain" warning?

The DKIM info displayed is "Invalid (Wrong signer ..."

See attached email and screenshot.

The "From" displayed indicates failure, whereas the "Sender" info
displayed shows no DKIM status.

In this case there is only one DKIM sig and it's domain matches the
"Sender" domain and the List-ID domain, and by the way, the
Received-SPF domain, too.

So we can't say anything with regard to taugh.com, but this mail sure
looks like it's legitimately from ietf.org.



Return-Path: <dmarc-bounces@ietf.org>
Received-SPF: pass (digilicious.com: domain of ietf.org designates 4.31.198.44 as permitted sender) client-ip=4.31.198.44; envelope-from=dmarc-bounces@ietf.org; helo=mail.ietf.org;
Received: from mail.ietf.org (mail.ietf.org. [4.31.198.44])
        by digilicious.com with ESMTPS id 9qxzpgar98nch
        for <dmarc@digilicious.com>
        (version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384 bits=256/256);
        Sat, 03 Jun 2017 04:15:06 -0700
Received: from ietfa.amsl.com (localhost [IPv6:::1])
	by ietfa.amsl.com (Postfix) with ESMTP id D930E128DE7;
	Sat,  3 Jun 2017 04:14:58 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=ietf.org; s=ietf1;
	t=1496488499; bh=8/fuKyp0i1LHjTIXELLQYRK8zP91qoXWInFyqZKZreA=;
	h=Date:From:To:In-Reply-To:Subject:List-Id:List-Unsubscribe:
	 List-Archive:List-Post:List-Help:List-Subscribe:Cc;
	b=lL5Wok30aZ6gfQLRSBgqRaRap3ApzgX7qeYOmvsTxTbWeuiJ1bbx/LGGzhqPVPzgK
	 1FVC6VpC+tKgVPh2Lo9NB5Xz7oGnCVoNk/4EcLqtX5sObZtvnvnU0/ATkkSk0Rwk1d
	 KfzwT04LTtKlKBCmajWSGr+HD4XKJub0G8aPcRxM=
X-Original-To: dmarc@ietfa.amsl.com
Delivered-To: dmarc@ietfa.amsl.com
Received: from localhost (localhost [127.0.0.1])
 by ietfa.amsl.com (Postfix) with ESMTP id A15EA128CF0
 for <dmarc@ietfa.amsl.com>; Sat,  3 Jun 2017 04:14:55 -0700 (PDT)
X-Virus-Scanned: amavisd-new at amsl.com
X-Spam-Flag: NO
X-Spam-Score: -0.5
X-Spam-Level: 
X-Spam-Status: No, score=-0.5 tagged_above=-999 required=5
 tests=[BAYES_05=-0.5, SPF_PASS=-0.001, URIBL_BLOCKED=0.001]
 autolearn=ham autolearn_force=no
Received: from mail.ietf.org ([4.31.198.44])
 by localhost (ietfa.amsl.com [127.0.0.1]) (amavisd-new, port 10024)
 with ESMTP id PyBpx07JRMdd for <dmarc@ietfa.amsl.com>;
 Sat,  3 Jun 2017 04:14:54 -0700 (PDT)
Received: from miucha.iecc.com (w6.iecc.com
 [IPv6:2001:470:1f07:1126::4945:4343])
 (using TLSv1 with cipher DHE-RSA-CAMELLIA256-SHA (256/256 bits))
 (No client certificate requested)
 by ietfa.amsl.com (Postfix) with ESMTPS id 76525127058
 for <dmarc@ietf.org>; Sat,  3 Jun 2017 04:14:54 -0700 (PDT)
Received: (qmail 31040 invoked from network); 3 Jun 2017 11:14:53 -0000
Received: from unknown (64.57.183.18)
 by mail1.iecc.com with QMQP; 3 Jun 2017 11:14:53 -0000
Date: 3 Jun 2017 11:14:31 -0000
Message-ID: <20170603111431.3820.qmail@ary.lan>
From: "John Levine" <johnl@taugh.com>
To: dmarc@ietf.org
In-Reply-To: <1496485938.3555.19.camel@wemonitoremail.com>
Organization: 
X-Headerized: yes
Mime-Version: 1.0
Archived-At: <https://mailarchive.ietf.org/arch/msg/dmarc/JV4uTmnvO5fU0gw5LuWgnXvAij4>
Subject: Re: [dmarc-ietf] Valimail and DMARC
X-BeenThere: dmarc@ietf.org
X-Mailman-Version: 2.1.22
Precedence: list
List-Id: "Domain-based Message Authentication, Reporting,
 and Compliance \(DMARC\)" <dmarc.ietf.org>
List-Unsubscribe: <https://www.ietf.org/mailman/options/dmarc>,
 <mailto:dmarc-request@ietf.org?subject=unsubscribe>
List-Archive: <https://mailarchive.ietf.org/arch/browse/dmarc/>
List-Post: <mailto:dmarc@ietf.org>
List-Help: <mailto:dmarc-request@ietf.org?subject=help>
List-Subscribe: <https://www.ietf.org/mailman/listinfo/dmarc>,
 <mailto:dmarc-request@ietf.org?subject=subscribe>
Cc: ken@wemonitoremail.com
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Errors-To: dmarc-bounces@ietf.org
Sender: "dmarc" <dmarc-bounces@ietf.org>

SW4gYXJ0aWNsZSA8MTQ5NjQ4NTkzOC4zNTU1LjE5LmNhbWVsQHdlbW9uaXRvcmVtYWlsLmNvbT4g
eW91IHdyaXRlOgo+TWFpbE1hbiBoYXMgc3VwcG9ydGVkIERNQVJDIGRvbWFpbnMgZm9yIGFnZXMg
dGhyb3VnaCBhIHNpbXBsZSBhZGRyZXNzIHJlLQo+d3JpdGluZyBtZWNoYW5pc20uIEl0IHdvcmtz
IHF1aXRlIHdlbGwuIFRoZSB2ZXJzaW9uIHJ1bm5pbmcgdGhpcyBsaXN0Cj4oMi4xLjIyKSBkZWZp
bml0ZWx5IHN1cHBvcnRzIGl0LCBpdCBqdXN0IG5lZWRzIHRvIGJlIGVuYWJsZWQuIMKgCgpUaGUg
SUVURiBoYXMgYSBsb25nLXJ1bm5pbmcgZGlzY3Vzc2lvbiBhYm91dCBob3cgdG8gZGVhbCB3aXRo
IERNQVJDCmFuZCBpcyBsb29raW5nIGF0IHNvbWUgb3B0aW9ucy4gIFB1dHRpbmcgdGhlIGxpc3Qn
cyBhZGRyZXNzIG9uIHRoZQpGcm9tOiBsaW5lIGlzIG5vdCBvbmUgb2YgdGhlIG9wdGlvbnMuCgpJ
dCB3b3VsZCBiZSB1dHRlcmx5IHVucHJvZHVjdGl2ZSB0byByZWFyZ3VlIHRoaXMgdG9waWMgaGVy
ZSwgc28gcGxlYXNlCmRvbid0LgoKUidzLApKb2huCgpfX19fX19fX19fX19fX19fX19fX19fX19f
X19fX19fX19fX19fX19fX19fX19fXwpkbWFyYyBtYWlsaW5nIGxpc3QKZG1hcmNAaWV0Zi5vcmcK
aHR0cHM6Ly93d3cuaWV0Zi5vcmcvbWFpbG1hbi9saXN0aW5mby9kbWFyYwo=

**Comment by gene-hightower** [comment]
![screenshot from 2017-06-04 14-16-19](https://cloud.githubusercontent.com/assets/3957811/26765648/27d1979e-4935-11e7-90f3-a1a189d3cc83.png)

**Comment by gene-hightower** [comment]
Another example (with failing sig from gmail.com)
![screenshot from 2017-06-04 14-54-02](https://cloud.githubusercontent.com/assets/3957811/26765683/c71ef95e-4935-11e7-8edf-591fc11d9fdf.png)
[email.txt](https://github.com/lieser/dkim_verifier/files/1050745/email.txt)

**Comment by lieser** [comment]
#### E-Mail from taugh.com
Either a custom sign rule or, if enabled, the [DMARC heuristic](https://github.com/lieser/dkim_verifier/wiki/Options#use-dmarc-to-heuristically-determine-if-an-e-mail-should-be-signed) incorrectly says that this e-mail should be signed by `taugh.com`. See the ["The add-on incorrectly says that en e-mail should be signed"](https://github.com/lieser/dkim_verifier/wiki/FAQ#the-add-on-incorrectly-says-that-en-e-mail-should-be-signed) point in the FAQ on how to avoid this.

If this is fixed, the DKIM signature by `ietf.org` should be shown as valid, with a "From is not in the signing domain" warning. Like I said previously, this warning can be disabled by a sign rule for the list.

#### E-Mail from google.com
The signature by `ietf.org` is probably not shown, because it also fails with "Invalid (Wrong signer ..." (you can check this in the error console of Thunderbird). As you want to ignore this for the mailing list, you have to add a sign rule for the mailing list and give it a higher priority than the one saying that it should be signed by google.com.

See also [this comment from me](https://github.com/lieser/dkim_verifier/issues/48#issuecomment-144373585) on how the displaying of multiple signatures is currently handled in the add-on.

----
Based on the Screenshots, I think I now get what you want (correct me if I'm worng): if the sender has added a signature, highlight the sender address based on that signature, similar to that is currently done for the from address.  
If the sign rules are not enough for you, I can add this as a feature request. But it will have a rather low priority, as I don't think many have enabled the displaying of the Sender header in Thunderbird.

**Comment by lieser** [comment]
I'm assuming the sign rules where enough for you. If not, please create a separate feature request for highlighting the sender address.
