### ISSUE TITLE
DKIM Signing capability

### ISSUE THREAD

**Issue by laertes-github** [lieser/dkim_verifier#89]
Would it be possible to enhance the DKIM Verifier to add the capability to add a DKIM Signature to outgoing Emails from Thunderbird? I realise this probably involves significant effort, but I can't find any other Add-On which provides this.

The Enigmail Add-On provides another style of Signature via GPG which is useful, but of course that doesn't integrate with DMARC.

Looking around, it seems to me that the only major Email client with DKIM Signing capability is Outlook; it would be nice to think that Thunderbird could get this feature soon.

**Comment by lieser** [comment]
I myself will not add DKIM signing to the add-on. Not only because, like you set, it would probably be a lot of work. I also do not think the E-Mail client is the right place to add the signature. It should be done by the sending server.

The reason for this is, that unlike in GPG, the signing entity is not an individual person, but rather a domain.

But I would probably add it if someone else is willing to implements it.

> Looking around, it seems to me that the only major Email client with DKIM Signing capability is Outlook; it would be nice to think that Thunderbird could get this feature soon.

Do you have a source for this? I never heard of the Outlook client being able to DKIM sign e-mails. I only know about the Outlook.com SERVICE signing outgoing e-mails for its domain.
